version: '3.8'
# expose backend/logs directory in backend container

services:
  backend:
    build:
      context: ./backend
    env_file:
      - backend/.env.development
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/logs:/app/logs
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: lms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lms_user -d lms"]
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 5s

volumes:
  postgres_data: